Add missing plugin-support.h include to model-infos.cpp
Added plugin-support.h include which provides obs_log function declaration.
This is needed for the models_info() function that uses obs_log.

This fixes compilation error:
- use of undeclared identifier 'obs_log'