Fix unused parameter warning in output_text function
Added (void) cast for possible_end_ts parameter which is only used
inside #ifdef ENABLE_WEBVTT block. Since ENABLE_WEBVTT is not defined
in obs-squawk, the parameter is unused and triggers -Werror,-Wunused-parameter.

This fixes compilation error:
- unused parameter 'possible_end_ts' [-Werror,-Wunused-parameter]